---
app_environment:
  prd:
    'BB.ca Web BG': http://bg2011.ihvweb.com/bg/init/?inst_id=217&impl_id=300&locale=en_us # the key is the application mame
    'BB.ca Web FR BG': http://bg2011.ihvweb.com/bg/init/?inst_id=218&impl_id=301&locale=fr_CA
    'BB.ca Mobile EN BG' : http://engageengine.ihvweb6.com/bgmw/#Guide/index/217/302 
    'BB.ca Mobile FR BG' : http://engageengine.ihvweb6.com/bgmw/#Guide/index/218/303 
    'bb_buying_guide': http://bg2011.ihvweb.com/bg/init/?inst_id=217&impl_id=300&locale=en_US
    'Dell BG': http://bg2011.ihvweb.com/bg/init/?inst_id=216&impl_id=304&sub_theme_id=sub_theme_dell_2011
    'ATT Web BG' : http://bg2011.ihvweb.com/bg/init/?inst_id=225&impl_id=307&locale=en_US&sub_theme_id=sub_theme_att_2011
    'Costco BG' : http://bg2011.ihvweb.com/bg/init/?inst_id=228&impl_id=315&locale=en_US&sub_theme_id=sub_theme_costco_2011
    'OfficeMax BG' : http://bg2011.ihvweb.com/bg/init/?inst_id=229&impl_id=316&locale=en_US&sub_theme_id=sub_theme_officemax_2011
    'Toshiba Laptops EN BG' : http://bg2011.ihvweb.com/bg/init/?inst_id=222&impl_id=305&locale=en_US&sub_theme_id=sub_theme_toshiba_2011
    'Toshiba Laptops FR BG' : http://bg2011.ihvweb.com/bg/init/?inst_id=223&impl_id=306&locale=fr_CA&sub_theme_id=sub_theme_toshiba_2011
    'Toshiba Laptops Mobile EN BG' : http://engageengine.ihvweb6.com/bgmwtl/#Guide/index/222/311
    'Toshiba Laptops Mobile FR BG' : http://engageengine.ihvweb6.com/bgmwtl/#Guide/index/223/312
    'Toshiba TV EN BG' : http://bg2011.ihvweb.com/bg/init/?inst_id=226&impl_id=309&locale=en_US&sub_theme_id=sub_theme_toshiba_tv_2011
    'Toshiba TV FR BG' : http://bg2011.ihvweb.com/bg/init/?inst_id=227&impl_id=310&locale=fr_CA&sub_theme_id=sub_theme_toshiba_tv_2011
    'Toshiba TV Mobile EN BG' : http://engageengine.ihvweb6.com/bgmwtv/#Guide/index/226/313
    'Toshiba TV Mobile FR BG' : http://engageengine.ihvweb6.com/bgmwtv/#Guide/index/227/314
    'OfficeMax Showcase' : http://showcase.ihvweb.com/officemax
    'BestBuy Showcase' : http://showcase.ihvweb.com/bestbuy 
    'HP Buying Guide': http://hp.com/buing_guide
  qa-test:
    'BB.ca Web BG': http://bg2011-qa.ihidevelopment.com/bg/init/?inst_id=217&impl_id=300&locale=en_US #the same application in different env
    'HP Buying Guide': http://qa.hp.com/buing_guide
  staging:
    'BB.ca Web BG': http://bg2011-static.ihidevelopment.com/bg/init/?inst_id=217&impl_id=300&locale=en_US
  development:
    'BB.ca Web BG': some url
    'HP Buying Guide': http://dev12.hp.com/buing_guide
    'climate' : http://localhost:3000/risk_reports
    
