---
app_environment:
  prd:
    'BB.ca Web BG': http://bg2011.ihvweb.com/bg/init/?inst_id=217&impl_id=300&locale=en_us # the key is the application mame

  qa-test:
    'BB.ca Web BG': http://bg2011-qa.ihidevelopment.com/bg/init/?inst_id=217&impl_id=300&locale=en_US #the same application in different env
